package io.novafoundation.nova.runtime.multiNetwork.exception

class DisabledChainException : Exception()
